import fs from 'node:fs';
import path from 'node:path';

const CSS = fs.readFileSync('node_modules/katex/dist/katex.min.css', 'utf8');
const FONT_DIR = 'node_modules/katex/dist/fonts';

// Replace every url(fonts/NAME.ext) reference with a data URL.
const out = CSS.replace(/url\(fonts\/([A-Za-z0-9_\-.]+)\)/g, (_, fname) => {
  const full = path.join(FONT_DIR, fname);
  if (!fs.existsSync(full)) return `url(fonts/${fname})`; // leave as-is
  const ext = path.extname(fname).slice(1);
  const mime = ext === 'woff2' ? 'font/woff2'
             : ext === 'woff' ? 'font/woff'
             : ext === 'ttf' ? 'font/ttf'
             : 'application/octet-stream';
  const b64 = fs.readFileSync(full).toString('base64');
  return `url(data:${mime};base64,${b64})`;
});

const js = `// AUTO-GENERATED by _build_katex_css.mjs — do not edit by hand.\n// KaTeX CSS with all font files inlined as data URLs so the stylesheet\n// works inside SVG <foreignObject> rasterised via <img src=\"data:...svg\">.\nexport const KATEX_INLINE_CSS = ${JSON.stringify(out)};\n`;

fs.writeFileSync('src/lib/katexInlineCss.ts', js);
console.log(`wrote src/lib/katexInlineCss.ts (${(out.length / 1024).toFixed(1)} KB CSS)`);
